[alembic]
script_location = alembic
file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s
prepend_sys_path = .
sqlalchemy.url = postgresql://revaive_user:revaive_password@localhost:5432/revaive_db

[logging]
default_handler_level = INFO
